### ISSUE TITLE
Failed load pubspec.yaml if contains dependencies from self hosted pub

### ISSUE THREAD

**Issue by ekasetiawans** [j4qfrost/pubspec#3]
Failed load pubspec.yaml if contains dependencies from self hosted pub

**Comment by dnys1** [comment]
The issue is in the [`ExternalHostedReference`](https://github.com/j4qfrost/pubspec/blob/master/lib/src/dependency.dart#L115) parsing. The hosted reference can take [two forms](https://dart.dev/tools/pub/dependencies#hosted-packages), neither of which matches the JSON serialization in this package.

## With `sdk: >=2.15.0`
```yaml
dependencies:
  transmogrify:
    hosted: https://some-package-server.com
    version: ^1.4.0
```

## Pre-2.15.0
```yaml
dependencies:
  transmogrify:
    hosted:
      name: transmogrify
      url: https://some-package-server.com
    version: ^1.4.0
```
