### ISSUE TITLE
saving pubspec with platform keywords results in null in the save file.

### ISSUE THREAD

**Issue by bsutton** [j4qfrost/pubspec#5]
If you read a pubspec.yaml with a 'platform:' keyword and then save the file the word null is added after each platform:

original pubspec
```
platforms: 
  linux:
  macos:
  windows:
```
After saving the pubspec
```
platforms: 
  linux: null
  macos: null
  windows: null
```

The platforms declaration also ends up at the end of the file rather than at than near the top of the file where it was originally placed.
